### ISSUE TITLE
Popular SMTP-Plugin (Postman) throwing error and stops working as soon as wp-staging-optimizer is active

### ISSUE THREAD

**Issue by peterbo** [wp-staging/wp-staging#184]
On staging, wp-staging-optimizer.php overrides the wp_mail function and changes its behaviour. Popular SMTP-Plugins have checks for this (legacy) behaviour and throw warnings or stop working. WP Staging should use the wp_mail hook to change the wp_mail behaviour, not override the function per se. For us (and possibly many others), it is an important feature to also test Email functionality / connectivity on staging environments.

![staging](https://user-images.githubusercontent.com/1018973/105172044-4edaad80-5b1f-11eb-8979-afe3bd108516.JPG)

**Comment by rene-hermenau** [comment]
Many popular mail plugins overwrite the wp_mail function or phpmailer on their own instead of using the available hooks. That's the only reason why we had to redeclare wp_mail() on the staging site to be able to disable mails for all available smtp mailing plugins out there.

If you don't want to disable mails you can create a new staging site and then disable the "send mail" checkbox in advanced settings.

Is this solving your issue or do you need another option?
